# Generated by Django 5.2 on 2025-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_publicacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
