# Generated by Django 5.2 on 2025-06-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livro_ano_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano_publicacao',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='livro',
            name='categorias',
            field=models.ManyToManyField(to='livros.categoria'),
        ),
    ]
